### ISSUE TITLE
Show line numbers in front of each news item or some page indicator

### ISSUE THREAD

**Issue by mihaitodor** [davep/oshit#11]
Thanks for continuing to spend time on this project! I'm really happy with it so far.

One small usability thing which might be very subjective is that on HN I purposely want to limit myself to scanning through the top 30 items. I usually avoid clicking "More" unless I really have time for it. In `oshit`, I have a hard time telling when I reach this limit. While showing the line number just like on HN will work for me, I can see how that might make the layout look too busy. Alternatively, I think some horizontal line or marker after each 30 items would also do the job for me at least. I don't care much about the actual rank position.

**Comment by davep** [comment]
Sounds like a reasonable request, especially if it limits time on HN. ;-)

I could make line numbers an on/off toggle (much like how the compact/relaxed mode works); another option could be (when I got the config dialog up and running; I think that's next on my list) to add a hard limit too so it only ever shows the top 30.

**Comment by mihaitodor** [comment]
Either of those would do the trick for me. Thank you for the quick reply! ❤️

**Comment by davep** [comment]
So far, numbers that can be toggled on/off, that display in both compact and relaxed mode:

![Screenshot 2024-01-16 at 21 45 05](https://github.com/davep/oshit/assets/28237/10376190-d6ab-4e5c-ae8c-5f0bc8a8520b)

![Screenshot 2024-01-16 at 21 45 21](https://github.com/davep/oshit/assets/28237/c1cbfe06-8b3b-4bf9-9d57-325afff867f0)

Still debating if they should be 0 or 1 based. ;-)

**Comment by mihaitodor** [comment]
Nice job! ❤️ 

> Still debating if they should be 0 or 1 based. ;-)

🤣 🤣 🤣

**Comment by davep** [comment]
All joking aside: do you think it makes sense to have the numbers on the right? I sense they stand out better that way; but on the other hand I feel there's a chance that they're not where your eyes might naturally fall.

**Comment by mihaitodor** [comment]
I'd have to spend some time with it, but since I don't usually maximise / resize my terminal window, I think it's fine the way you implemented it. I can see the numbers and the left hand side would get very busy otherwise.

**Comment by davep** [comment]
[v0.5.0 is live](https://github.com/davep/oshit/releases/tag/v0.5.0) -- the limits I suggested are in there, but can only be modified via the config file; they'll be better exposed when I add the proper configuration dialog.

**Comment by mihaitodor** [comment]
That looks awesome, I love it! ❤️  Indeed, the numbers don't pop up in my direct line of sight, but I like that since I take a peek towards the right while scrolling.

Hope you won't hate me, but I have some more ideas which I raised in a discussion thread: #13 (lucky number 13 😅)

**Comment by davep** [comment]
Glad to hear it; and more ideas are always very welcome. I'll take a proper look later. :-)
