### ISSUE TITLE
Potential UI bug

### ISSUE THREAD

**Issue by mihaitodor** [davep/oshit#21]
I installed the latest version and I navigated to the `Show` section and pressed `C` key to reveal the comments and I think I hit a layout overflow issue, which I think is due to the block of text attached to the article being to big (see [here](https://news.ycombinator.com/item?id=39232572)). I can work around it by enlarging the window a bit.

<img width="884" alt="image" src="https://github.com/davep/oshit/assets/788216/897621e9-917e-4bec-b8ca-599d4b1b2330">

**Comment by davep** [comment]
Yeah, good point, I should make the text of a post more akin to a comment (just obvious that it isn't a comment) and have it something that scrolls out of view as you scroll down the comments.

**Comment by davep** [comment]
Hopefully improved by [v0.9.0](https://github.com/davep/oshit/releases/tag/v0.9.0). :-)

**Comment by mihaitodor** [comment]
Yep, that works a lot better now, thank you! <3

**Comment by davep** [comment]
Glad to hear it; you're most welcome. :-)
